theme: just-the-docs
title: tapan-s-blog
description: Articles on Automation, Testing, DevOps and AI.
url: "https://TapanPatra.github.io"
baseurl: "/tapan-s-blog"
author: Tapan Kumar Patra
just_the_docs:
  search_enabled: true
nav_external_links: []
